name: 🐛 Bug report
description: Report a reproducible bug or regression in this library.
labels: [bug]
assignees:
  - zoontek
body:
  - type: markdown
    attributes:
      value: |
        # Bug report

        👋 Hi!

        **🚨 Please read the following carefully before opening a new issue 🚨**
        *(Your issue may be closed if it doesn't provide the required pieces of information)*

        Before submitting a new issue, please:

        - Test using the latest release of the library, as maybe your bug has been already fixed.
        - Check for possible duplicate issues, with possible answers.

        Is this still needed? Fill the form 👇
  - type: textarea
    id: summary
    attributes:
      label: Bug summary
      description: |
        Provide a clear and concise description of what the bug is.
        If needed, you can also provide other samples: error messages / stack traces, screenshots, videos, etc.
    validations:
      required: true
  - type: input
    id: library-version
    attributes:
      label: Library version
      description: What version of the library are you using?
      placeholder: "x.x.x"
    validations:
      required: true
  - type: textarea
    id: browser-info
    attributes:
      label: Environment info
      description: Go to [WhatIsMyBrowser](https://www.whatismybrowser.com) and copy / paste your browser & OS names + versions.
      render: shell
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: |
        - You must provide a clear list of steps and code to reproduce the problem.
        - Keep the code reproducing the bug as simple as possible, with the minimum amount of code required to reproduce the issue. See https://stackoverflow.com/help/mcve.
        - Either re-create the bug using the repository's example app or link to a GitHub repository with code that reproduces the bug.
        - Explain the steps we need to take to reproduce the issue:
      value: |
        1. …
        2. …
    validations:
      required: true
  - type: textarea
    id: reproducible-sample-code
    attributes:
      label: Reproducible sample code
      description: Please add minimal runnable repro as explained above so that the bug can be tested in isolation.
      render: ts
    validations:
      required: true
